export const TURN_ON_THRESHOLD = 800;
export const DOUBLE_PRESS_THRESHOLD = 300;
export const SHOW_CHARGE_INDICATOR_FROM_PRESS_THRESHOLD = 400;
export const CHARGE_INDICATOR_AUTO_SHUTDOWN_TIMER = 4000;
